### ISSUE TITLE
`show` doesn't work in python 3.13 but works in 3.12

### ISSUE THREAD

**Issue by dvd101x** [CadQuery/cadquery#1944]
## To Reproduce

Making a new venv on 3.13.9 installing cadquery (pip) and running the example for show
```python
from cadquery import *
from cadquery.vis import show

w = Workplane().sphere(1).split(keepBottom=True) - Workplane().sphere(0.5)
r = w.faces('>Z').fillet(0.1)

# Show the result
show(r, alpha=0.5)
```
Throws an error, but the same procedure of creating a venv in 3.12.10, installing cadquery and running the show example works as expected.

I found it while trying to make a mixture of cadquery and sdf (like [microgen](https://github.com/3MAH/microgen)), I don't specifically need 3.13, just filling the report in case it helps.

## Backtrace

```
^CVTK not installed
Traceback (most recent call last):
  File "/Users/david/Documents/code/cq2/test.py", line 1, in <module>
    from cadquery import *
  File "/Users/david/Documents/code/cq2/lib/python3.13/site-packages/cadquery/__init__.py", line 11, in <module>
    from .occ_impl.shapes import (
    ...<9 lines>...
    )
  File "/Users/david/Documents/code/cq2/lib/python3.13/site-packages/cadquery/occ_impl/shapes.py", line 292, in <module>
    from OCP.IVtkOCC import IVtkOCC_Shape, IVtkOCC_ShapeMesher
ImportError: cannot import name 'IVtkOCC_Shape' from 'OCP.IVtkOCC' (/Users/david/Documents/code/cq2/lib/python3.13/site-packages/OCP/IVtkOCC/__init__.py)
```

## Environment

OS:
MaxOS 26.1
Sorry, I wasn't using conda, I was using pip.

Was CadQuery installed using Conda?: 
Output of `conda list` from your active Conda environment:
```
```

Using: 
Python interpreter

**Comment by jmwright** [comment]
Is this an Intel-based Mac, or an M1, etc?

**Comment by dvd101x** [comment]
Thanks. 

It's not an intel, it's an M series.

**Comment by adam-urbanczyk** [comment]
What *is* in your working and not working env? Does it work as expected with conda packaged version?

**Comment by dvd101x** [comment]
In both there is noting but cadquery. Just `pip install cadquery`. I found out by work in another venv with vtk, cadquery, numpy and jax. But replicated a minimal example by making two new venvs with just cadquery.

I don't have conda. But I can try and report back.

**Comment by bioerrorlog** [comment]
I had the same output on M2 Mac, Python 3.11, cadquery 2.8.0, installed with pip.

In my case it turned out not to be a real error.
The fix was simply to wait instead of pressing Ctrl+C.


```
^CVTK not installed
Traceback (most recent call last):
  File "/Users/bioerrorlog/dev/fusion-energy-sandbox/cadquery-introduction/main.py", line 1, in <module>
    import cadquery as cq
  File "/Users/bioerrorlog/dev/fusion-energy-sandbox/cadquery-introduction/.venv/lib/python3.11/site-packages/cadquery/__init__.py", line 11, in <module>
    from .occ_impl.shapes import (
  File "/Users/bioerrorlog/dev/fusion-energy-sandbox/cadquery-introduction/.venv/lib/python3.11/site-packages/cadquery/occ_impl/shapes.py", line 297, in <module>
    from OCP.IVtkOCC import IVtkOCC_Shape, IVtkOCC_ShapeMesher
ImportError: cannot import name 'IVtkOCC_Shape' from 'OCP.IVtkOCC' (/Users/bioerrorlog/dev/fusion-energy-sandbox/cadquery-introduction/.venv/lib/python3.11/site-packages/OCP/IVtkOCC/__init__.py)
```

Note that `^CVTK not installed`, which also appears in your traceback above, is actually two separate outputs: the `^C` is the Ctrl+C itself, and `VTK not installed` is what gets printed as a result of that interrupt.

The import just takes a while — in my case, around 40s on first run. I assumed it had hung and interrupted it.

The interrupt gets turned into a misleading message by the bare `except` here:

```python
# site-packages/OCP/IVtkOCC/__init__.py
try:
  import vtk
  from ..OCP.IVtkOCC import *
except:
  print('VTK not installed')
```

**Comment by adam-urbanczyk** [comment]
Thanks for figuring this out @bioerrorlog. @bernhard-42 what is your take on this? I'm not loving that cadquery-ocp makes functional changes to canonical ocp sources.

**Comment by bernhard-42** [comment]
@adam-urbanczyk There are no functional changes to canonical ocp sources. The sources get translated 1:1 and the resulting OCP*.so is unchanged.
However, in pypi world, we need to properly support VTK from pypi.
This is not as easy as in anaconda. You can compile against pypi VTK (with some tricks), but then you need to ensure that at runtime OCP finds the right VTK. For MacOS and Linux ocp-build-system patches the vtk lib path as `rpath` into the `*.so` file.
But for Windows, the PATH variable needs to be changed so that OCP*.so finds VTK dlls.
The only way I found was to add this hierarchy of imports to `site-packages/OCP`:

```python
OCP
├── __init__.py
├── Adaptor2d
│   └── __init__.py
├── Adaptor3d
│   └── __init__.py
├── AdvApp2Var
│   └── __init__.py
├── AdvApprox
│   └── __init__.py
├── AIS
│   └── __init__.py
├── APIHeaderSection
│   └── __init__.py
├── AppBlend
│   └── __init__.py
...
```

and use for Windows this [init file](https://github.com/CadQuery/ocp-build-system/blob/main/pypi/__init__win.py).
For cadquery-ocp to be consistent across platforms, Macos and Linux use the same tree with this [init file](https://github.com/CadQuery/ocp-build-system/blob/main/pypi/__init__.py).

The only bug here is to not use:
```python
try:
  import vtk
  from ..OCP.IVtkOCC import *
except ImportError:              # <= sic!
  print('VTK not installed')
```
or omit the `try` clause completely. I think we needed it for build123d (or for Python 3.13 cadquery_vtk which we retired now), but in the meantime build123d is decoupled from VTK, so it is not needed any more.

Happy to change this in the next release.

However, to stress that again, cadquery-ocp does not make functional changes to canonical ocp sources. We just have to adapt the runtime behaviour to the pypi ecosystem.

CC: @jmwright @jdegenstein

**Comment by bernhard-42** [comment]
Plus, to get back to original issue "show doesn't work in python 3.13 but works in 3.12"
We tried cadquery_vtk for python 3.13 and OCCT 7.8, our own vtk package. This has led to issues and we have retired it. It doesn't exist for cadquery_ocp 7.9 any more.

**Comment by adam-urbanczyk** [comment]
Well I can understand the path story, but adding a `try..except...`  is a functional change that is the root cause of this issue AFAICT. I'd prefer that no such constructs are added. I see no reason why the `ImportError` cannot be handled on the build123 side (if it is even really needed).

**Comment by bernhard-42** [comment]
I remove it in the next release of ocp-build-system. It is not needed any more, see https://github.com/CadQuery/ocp-build-system/issues/63

I don't really recall, too long ago, but it was needed and we couldn't handle in build123d - yet is was poorly implemented.
But it will anyhow vanish
