### ISSUE TITLE
radiusArc not available

### ISSUE THREAD

**Issue by tolot27** [CadQuery/cadquery#61]
The function `radiusArc` introduced with https://github.com/dcowden/cadquery/pull/254 is not available in cadquery-occ.

```
AttributeError: 'Workplane' object has no attribute 'radiusArc'
```

**Comment by justbuchanan** [comment]
Hi @tolot27 , thanks for bringing this up. There are a lot of changes in the main (dcowden) cadquery that haven't yet been merged into this occ fork yet. Once we merge the latest changes, this issue and #62 should be fixed.

I filed an issue for merging here: https://github.com/CadQuery/cadquery/issues/9.

**Comment by tolot27** [comment]
This issue was fixed with #65.
