### ISSUE TITLE
 Does OCP work in OCCT 7.5.2 ?

### ISSUE THREAD

**Issue by a09418849** [CadQuery/cadquery#809]
I used the general way to install cadquery  :
```
conda install -c conda-forge -c cadquery cadquery=master
```

and it showed the warning  :

```
type object 'OCP.BRepGProp.BRepGProp' has no attribute 'LinearProperties_s'
```

I noticed that the OCCT has been updated to version=7.5.2, but in cadquery is 7.5.1 
So I try to install OCCT 7.5.1 first  :
```
conda install -c conda-forge -c trelau pyocct=7.5.1.1
```
And then it works , but I don't know why.

Sorry for my bad English.

Envirements :
```
# Name                    Version                   Build  Channel
anyio                     3.2.1                    pypi_0    pypi
argon2-cffi               20.1.0           py38h2bbff1b_1
async_generator           1.10               pyhd3eb1b0_0
attrs                     21.2.0             pyhd3eb1b0_0
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
bleach                    3.3.0              pyhd3eb1b0_0
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.25            haa95532_1
cadquery                  master                    py3.8    cadquery
cadquery-massembly        0.9.0                    pypi_0    pypi
certifi                   2021.5.30        py38haa95532_0
cffi                      1.14.5           py38hcd4344a_0
chardet                   4.0.0                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0
console_shortcut          0.1.1                         4
curl                      7.77.0               h789b8ee_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
decorator                 5.0.9              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
double-conversion         3.1.5                h0e60522_2    conda-forge
eigen                     3.3.9                h2d74725_1    conda-forge
entrypoints               0.3                      py38_0
expat                     2.4.1                h39d44d4_0    conda-forge
ezdxf                     0.16.4           py38hbd9d945_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeimage                 3.18.0               hfcb8cd7_7    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10                     pypi_0    pypi
ilmbase                   2.5.5                h12d4b20_0    conda-forge
importlib-metadata        3.10.0           py38haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
intel-openmp              2021.2.0           h57928b3_616    conda-forge
ipydatawidgets            4.2.0                    pypi_0    pypi
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.22.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3                    pypi_0    pypi
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.17.0                   py38_0
jinja2                    3.0.1              pyhd3eb1b0_0
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.6                    pypi_0    pypi
jsoncpp                   1.9.4                h2d74725_2    conda-forge
jsonschema                3.2.0                      py_2
jupyter-cadquery          2.2.0                    pypi_0    pypi
jupyter-cadquery-widgets  2.0.2                    pypi_0    pypi
jupyter-server            1.9.0                    pypi_0    pypi
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyterlab                3.0.16                   pypi_0    pypi
jupyterlab-server         2.6.0                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.19.1               hbae68bd_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.77.0               h789b8ee_0    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libraw                    0.20.2               hee1bdec_1    conda-forge
libsodium                 1.0.18               h62dcd97_0
libssh2                   1.9.0                h680486a_6    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.3.0                h0c97f57_1    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzip                    1.8.0                hfed4ece_0    conda-forge
loguru                    0.5.3            py38haa244fe_2    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                2.0.1            py38h2bbff1b_0
matplotlib                3.4.2                    pypi_0    pypi
mistune                   0.8.4           py38he774522_1000
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1
nbclassic                 0.3.1                    pypi_0    pypi
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
notebook                  6.4.0            py38haa95532_0
nptyping                  1.4.2              pyhd8ed1ab_0    conda-forge
numpy                     1.21.0           py38h09042cb_0    conda-forge
occt                      7.5.1                h60997fb_2    conda-forge
ocp                       7.5.1beta               1_py3.8    cadquery
openexr                   2.5.5                hab3b255_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1k               h2bbff1b_0
orbitcontrol-patch        0.1.0                    pypi_0    pypi
packaging                 20.9               pyhd3eb1b0_0
pandocfilters             1.4.3            py38haa95532_1
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.2           py38haa95532_0
proj                      7.2.0                h1cfcee9_2    conda-forge
prometheus_client         0.11.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
pugixml                   1.11.4               h0e60522_0    conda-forge
pycparser                 2.20                       py_2
pygments                  2.9.0              pyhd3eb1b0_0
pyocct                    7.5.1.1          py38h7e01d4e_0    trelau
pyparsing                 2.4.7              pyhd3eb1b0_0
pyrsistent                0.17.3           py38he774522_0
python                    3.8.10               hdbf39b2_7
python-dateutil           2.8.1              pyhd3eb1b0_0
python_abi                3.8                      2_cp38    conda-forge
pythonocc-core            7.5.1            py38h030ce49_0    conda-forge
pythreejs                 2.3.0                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywin32                   227              py38he774522_1
pywinpty                  0.5.7                    py38_0
pyzmq                     20.0.0           py38hd77b12b_1
qt                        5.12.9               h5909a2a_4    conda-forge
rapidjson                 1.1.0             ha925a31_1002    conda-forge
requests                  2.25.1                   pypi_0    pypi
requests-unixsocket       0.2.0                    pypi_0    pypi
scipy                     1.7.0            py38he847743_0    conda-forge
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38haa95532_0
sidecar                   0.5.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0
sniffio                   1.2.0                    pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
tbb                       2020.2               h2d74725_4    conda-forge
tbb-devel                 2020.2               h2d74725_4    conda-forge
terminado                 0.9.4            py38haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py38h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
traittypes                0.2.1                    pypi_0    pypi
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
typish                    1.9.2              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
utfcpp                    3.2.1                h57928b3_0    conda-forge
vc                        14.2                 h21ff451_1
voila                     0.2.10                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       9.0.1           no_osmesa_py38h8c3c96c_109    conda-forge
wcwidth                   0.2.5                      py_0
webcolors                 1.11.1                   pypi_0    pypi
webencodings              0.5.1                    py38_1
websocket-client          1.1.0                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    pypi_0    pypi
win32_setctime            1.0.3                      py_0    conda-forge
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

**Comment by fedorkotov** [comment]
Maximum supported OCP version is 7.5.1. See https://github.com/CadQuery/cadquery/pull/792 and #790

**Comment by jmwright** [comment]
For now, the following conda install line should produce a working environment.
```
conda install -c cadquery -c conda-forge cadquery=master ocp=7.5.1
```

**Comment by fedorkotov** [comment]
@jmwright Maybe conda installation command should be updated in [README](https://github.com/CadQuery/cadquery#getting-started)?

**Comment by jmwright** [comment]
It's my understanding that it should be fixed fairly soon so that the original line with just `cadquery=master` will work again. [Reference](https://github.com/CadQuery/cadquery/issues/790#issuecomment-869923900)

**Comment by adam-urbanczyk** [comment]
Duplicate of #790
